spring:
  profiles:
    active: dev
  boot:
    admin:
      client:
        enabled: false
  mail:
    host: smtp.mail.ovh.net
    port: 465
    username: kontakt@xsware.pl
    password: ${MY_SMTP_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000

server:
  error:
    whitelabel:
      enabled: false
    include-exception: false
    include-stacktrace: never
    include-message: never
    include-binding-errors: never
